// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krntnxxdaoixngwgtsxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtybnRueHhkYW9peG5nd2d0c3h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MjQ1MzQsImV4cCI6MjA2MTUwMDUzNH0.OYNFvMS3jK9gdN0L_czYidSorUciWDE8AruJz7WggWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);